name: build-and-deploy-s3

on:
  push:
    branches: [ main ]

env:
  NODE_VERSION: '14.18.1'

jobs:
  build-strapi:
    runs-on: ubuntu-latest
    steps:
      - name: Use actions/checkout@v2
        uses: actions/checkout@v2

      - name: Set up Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install node dependencies
        run: npm install

  deploy:
    runs-on: ubuntu-latest
    needs: [ build-strapi ]
    environment:
      name: Production
      url: https://strapi.umami.pinciuc.com
    steps:
      - name: Use actions/checkout@v2
        uses: actions/checkout@v2

      - name: Set up Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install node dependencies
        run: npm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # if you have/need it
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Create zip archive
        run: zip -y -q -x ".git/*" -r ${{ secrets.AWS_S3_DEPLOY_FILENAME }} .

      - name: Copy archive to S3 with the AWS CLI
        run: aws s3 cp ${{ secrets.AWS_S3_DEPLOY_FILENAME }} s3://${{ secrets.AWS_S3_BUCKET }}/${{ secrets.AWS_S3_DEPLOY_PATH }}/
